#!/usr/bin/env python3
"""Generate the private target-Mac .env without printing either API key."""

from __future__ import annotations

import argparse
import ipaddress
import os
from pathlib import Path
import re
import secrets
import subprocess


ROOT = Path(__file__).resolve().parent.parent


def dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        values[name.strip()] = value.strip().strip('"').strip("'")
    return values


def tailscale_ip() -> str:
    output = subprocess.run(
        ["/sbin/ifconfig"], capture_output=True, text=True, check=True
    ).stdout
    for match in re.finditer(r"^\s*inet\s+(\d+\.\d+\.\d+\.\d+)\b", output, re.MULTILINE):
        address = ipaddress.ip_address(match.group(1))
        if address in ipaddress.ip_network("100.64.0.0/10"):
            return str(address)
    raise SystemExit("no active Tailscale IPv4 address found")


def safe(value: str, name: str) -> str:
    if not value or any(character in value for character in "\r\n"):
        raise SystemExit(f"invalid {name}")
    return value


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bridge-host", default=None)
    parser.add_argument("--bridge-port", type=int, default=8788)
    parser.add_argument("--reference-audio")
    args = parser.parse_args()

    host = safe(args.bridge_host or tailscale_ip(), "bridge host")
    if not 1 <= args.bridge_port <= 65535:
        raise SystemExit("bridge port must be between 1 and 65535")

    hermes_key = safe(
        os.environ.get("API_SERVER_KEY")
        or os.environ.get("HERMES_API_KEY", ""),
        "Hermes API key from API_SERVER_KEY or HERMES_API_KEY",
    )
    current = dotenv(ROOT / ".env")
    bridge_key = current.get("BRIDGE_API_KEY") or secrets.token_hex(32)

    reference = ""
    provider = "macos"
    command = ""
    if args.reference_audio:
        reference_path = Path(args.reference_audio).expanduser().resolve()
        if not reference_path.is_file():
            raise SystemExit(f"reference audio not found: {reference_path}")
        reference = str(reference_path)
        provider = "command"
        command = (
            f"{ROOT}/.venv/bin/python {ROOT}/scripts/chatterbox_tts.py "
            "--text-file {text_file} --output {output_file} --language {language} "
            "--reference {reference_audio}"
        )

    lines = [
        "# Generated by scripts/configure_target.py; do not commit.",
        f"BRIDGE_API_KEY={safe(bridge_key, 'bridge API key')}",
        f"BRIDGE_HOST={host}",
        f"BRIDGE_PORT={args.bridge_port}",
        "HERMES_BASE_URL=http://127.0.0.1:8642",
        f"HERMES_API_KEY={hermes_key}",
        f"TTS_PROVIDER={provider}",
        "TTS_VOICE_EN=Samantha",
        "TTS_VOICE_HI=Lekha",
        "TTS_VOICE_FR=Thomas",
        f"TTS_REFERENCE_AUDIO={reference}",
        f"TTS_COMMAND='{command}'" if command else "TTS_COMMAND=",
        "CHATTERBOX_MODEL=mlx-community/chatterbox-multilingual-v3",
        "CHATTERBOX_MODEL_REVISION=03565773edd72e949572557597af8063bb49a18a",
        f"HF_HOME={ROOT}/work/voice-models",
        "STT_COMMAND=",
        "AUDIO_TTL_SECONDS=3600",
        "MAX_CONCURRENT_REQUESTS=2",
        "MAX_TEXT_CHARS=2000",
        "",
    ]
    destination = ROOT / ".env"
    temporary = ROOT / ".env.tmp"
    temporary.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(temporary, 0o600)
    os.replace(temporary, destination)
    print(f"configured {destination} for {host}:{args.bridge_port}")
    print(f"TTS provider: {provider}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
